<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EBJ4468" name="com.test.DdataProviderTest" tests="5" failures="0" timestamp="9 Feb 2017 09:49:44 GMT" time="0.021" errors="1">
  <testcase name="doTestNG1" time="0.002" classname="com.test.DdataProviderTest"/>
  <testcase name="doTestNG1" time="0.007" classname="com.test.DdataProviderTest"/>
  <testcase name="doTestNG2" time="0.002" classname="com.test.DdataProviderTest"/>
  <testcase name="doTestNG2" time="0.001" classname="com.test.DdataProviderTest"/>
  <testcase name="doTestNG" time="0.009" classname="com.test.DdataProviderTest">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 2 parameters but the method com.test.DdataProviderTest#doTestNG takes 1">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 2 parameters but the method com.test.DdataProviderTest#doTestNG takes 1
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1225)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- doTestNG -->
</testsuite> <!-- com.test.DdataProviderTest -->
